### PR TITLE
Add support to set a single thread executor for kinesis consumer

### PR DESCRIPTION
**Pull request by peakxu**
@blinsay, please review.

In some use cases, it might be useful to allow setting single threaded execution in the consumers. This adds an additional optional arg to KCL consumer. Default maintains original behavior of multithreading.

### CODE REVIEW

**Comment by blinsay** [comment]
I think the way I want to do this is to use an an `:executor` key in the config that's passed in to `KCL.new` so people can add any executor of their choice. It'd look something like:

```ruby
config = {
  app: 'myapp',
  stream: 'some-stream',
  executor: Executors.new_single_thread_executor,
}

worker = Telekinesis::Consumer::KCL.new(config) do
  SomeProcessor.new
end
```

I'm going to close this PR and try and work on this tonight. Mind opening an issue with this feature request in the mean time?

Also, out of curiosity, what's your use-case?

**Comment by peakxu** [comment]
Good call. Will open an issue. My particular use-case is running some third party code which we aren't sure is thread-safe. Would like to experiment w/ different executors.

**Comment by peakxu** [comment]
I don't seem to have permissions for opening issues on this repo? Going to the /issues/new link 404s for me.

**Comment by blinsay** [comment]
Whoops! Should be all set now.

**Pull request closed without merging**
